# Generated by Django 6.0.4 on 2026-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teac_name', models.CharField(max_length=255, null=True)),
                ('teac_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('teac_id', models.PositiveIntegerField(unique=True)),
                ('teac_address', models.TextField(null=True)),
                ('teac_contact', models.CharField(null=True)),
                ('teac_age', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
