# Generated by Django 6.0.4 on 2026-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=255, null=True)),
                ('stud_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('stud_id', models.PositiveIntegerField(unique=True)),
                ('stud_address', models.TextField(null=True)),
                ('stud_contact', models.PositiveIntegerField(null=True)),
                ('stud_age', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
