# Generated by Django 6.0.4 on 2026-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='stud_contact',
            field=models.CharField(null=True),
        ),
    ]
